name: wincalc_engine
description: Dart FFI bindings to the Windows Calculator engine, providing standard, scientific, and programmer calculator functionality.
version: 0.0.3
homepage: https://github.com/dongfengweixiao/wincalc_engine
repository: https://github.com/dongfengweixiao/wincalc_engine
issue_tracker: https://github.com/dongfengweixiao/wincalc_engine/issues

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.4
  hooks: ^1.0.0
  logging: ^1.3.0
  native_toolchain_c: ^0.17.4
  # path: ^1.9.0

dev_dependencies:
  ffigen: ^20.1.1
  lints: ^6.0.0
  test: ^1.25.6
